[workspace]
authors = [
    "The Sooner Rover Team",                        # :D
    "Tyler Roman <tyler73750@gmail.com>",
    "Logan Murphy <logan.m.murphy-11@ou.edu>",
    "Barrett Ray <contact@barretts.club>",
    "Brendan Ford <bford@axmilius.com>",
    "Carson Burnett <carsonburnett379@icloud.com>",
    "Mizael Morales <mizaelmorales321@gmail.com>",
]
channels = ["conda-forge", "robostack-jazzy"]
name = "auto_ros2"
platforms = ["linux-aarch64", "linux-64", "osx-arm64", "osx-64"]
version = "0.2.0"

[dependencies]
# note: all the lil blocks down here are related groups, each in alphabetical
# order.
#
# feel free to violate that rule if you're in a pinch, but fix it before
# committing; otherwise, this'll get messy... quick!

# command-line tools (not for compilation)
gh = { version = ">=2.78.0", channel = "conda-forge" }            # GitHub CLI
just = { version = ">=1.42.4,<2", channel = "conda-forge" }       # `just` command runner
lazygit = { version = ">=0.54.2,<0.55", channel = "conda-forge" } # `lazygit` TUI tool

# build tools (e.g., c compiler, rust, glibc)
c-compiler = { channel = "conda-forge" }
clang = { channel = "conda-forge" }
clangxx = { channel = "conda-forge" }
cxx-compiler = { channel = "conda-forge" }
glib = { channel = "conda-forge" }
make = { version = "==4.4.1", channel = "conda-forge" }
rust = { version = ">=1.89.0", channel = "conda-forge" }
rust-src = { version = ">=1.89.0", channel = "conda-forge" }

# system python dependencies
basedpyright = { version = ">=1.31.3", channel = "conda-forge" }
numpy = ">=1.26,<2"
python = "3.12.*"
ruff = ">=0.12.11"
uv = { version = "==0.8.11", channel = "conda-forge" }

# ros 2 tooling (e.g., colcon, ros2-cli)
colcon-core = { channel = "conda-forge" }
colcon-cmake = { channel = "conda-forge" }
colcon-common-extensions = { channel = "conda-forge" }
colcon-mixin = { channel = "conda-forge" }
colcon-ros = { channel = "conda-forge" }
colcon-test-result = { channel = "conda-forge" }
ros-jazzy-cyclonedds = { channel = "robostack-jazzy" }
ros-jazzy-ros2cli = { channel = "robostack-jazzy" }
ros-jazzy-ros2cli-common-extensions = { channel = "robostack-jazzy" }
ros2-distro-mutex = { version = ">=0.7", channel = "robostack-jazzy" } # IMPORTANT! change ver if needed

# ros 2 build packages (for ament, cmake, and colcon)
ros-jazzy-ament-cmake-auto = { channel = "robostack-jazzy" }
ros-jazzy-ament-cmake-clang-format = { channel = "robostack-jazzy" }
ros-jazzy-ament-cmake = { channel = "robostack-jazzy" }
ros-jazzy-ament-cmake-core = { channel = "robostack-jazzy" }
ros-jazzy-ament-cmake-pytest = { channel = "robostack-jazzy" }
ros-jazzy-ament-lint-auto = { channel = "robostack-jazzy" }
ros-jazzy-ament-pep257 = { channel = "robostack-jazzy" }
ros-jazzy-launch-pytest = { channel = "robostack-jazzy" }
ros-jazzy-launch-testing-ament-cmake = { channel = "robostack-jazzy" }
ros-jazzy-python-cmake-module = { channel = "robostack-jazzy" }
ros-jazzy-rosidl-default-generators = { channel = "robostack-jazzy" }
ros-jazzy-rosidl-default-runtime = { channel = "robostack-jazzy" }

# ros 2 message pkgs
ros-jazzy-action-msgs = { channel = "robostack-jazzy" }
ros-jazzy-actionlib-msgs = { channel = "robostack-jazzy" }
ros-jazzy-diagnostic-msgs = { channel = "robostack-jazzy" }
ros-jazzy-geographic-msgs = { channel = "robostack-jazzy" }
ros-jazzy-geometry-msgs = { channel = "robostack-jazzy" }
ros-jazzy-nav2-msgs = { channel = "robostack-jazzy" }
ros-jazzy-rcl-interfaces = { channel = "robostack-jazzy" }
ros-jazzy-ros-gz-interfaces = { channel = "robostack-jazzy" }
ros-jazzy-sensor-msgs = { channel = "robostack-jazzy" }
ros-jazzy-shape-msgs = { channel = "robostack-jazzy" }
ros-jazzy-std-msgs = { channel = "robostack-jazzy" }
ros-jazzy-std-srvs = { channel = "robostack-jazzy" }
ros-jazzy-stereo-msgs = { channel = "robostack-jazzy" }
ros-jazzy-trajectory-msgs = { channel = "robostack-jazzy" }

# ros 2 launch file pkgs
ros-jazzy-launch = { channel = "robostack-jazzy" }
ros-jazzy-launch-ros = { channel = "robostack-jazzy" }
ros-jazzy-launch-testing = { channel = "robostack-jazzy" }

# ros 2 important runtime pkgs (like Nav2)
ros-jazzy-controller-manager = { channel = "robostack-jazzy" }
ros-jazzy-cv-bridge = { channel = "robostack-jazzy" }
ros-jazzy-depthimage-to-laserscan = { channel = "robostack-jazzy" }
geographiclib = { channel = "conda-forge" } # replaces `ros-humble-geodesy` in `jazzy`+
ros-jazzy-image-proc = { channel = "robostack-jazzy" }
ros-jazzy-joint-state-broadcaster = { channel = "robostack-jazzy" }
ros-jazzy-joint-state-publisher = { channel = "robostack-jazzy" }
ros-jazzy-nav2-behavior-tree = { channel = "robostack-jazzy" }
ros-jazzy-nav2-bringup = { channel = "robostack-jazzy" }
ros-jazzy-nav2-common = { channel = "robostack-jazzy" }
ros-jazzy-nav2-simple-commander = { channel = "robostack-jazzy" }
ros-jazzy-pointcloud-to-laserscan = { channel = "robostack-jazzy" }
ros-jazzy-rcl = { channel = "robostack-jazzy" }
ros-jazzy-rclcpp = { channel = "robostack-jazzy" }
ros-jazzy-rclpy = { channel = "robostack-jazzy" }
ros-jazzy-robot-localization = { channel = "robostack-jazzy" }
ros-jazzy-robot-state-publisher = { channel = "robostack-jazzy" }
ros-jazzy-ros2-control = { channel = "robostack-jazzy" }
ros-jazzy-ros2-controllers = { channel = "robostack-jazzy" }
ros-jazzy-stereo-image-proc = { channel = "robostack-jazzy" }
ros-jazzy-tf-transformations = { channel = "robostack-jazzy" }
ros-jazzy-tf2 = { channel = "robostack-jazzy" }
ros-jazzy-tf2-ros = { channel = "robostack-jazzy" }
ros-jazzy-vision-opencv = { channel = "robostack-jazzy" }

# ros 2 debugging pkgs
ros-jazzy-tf2-tools = { channel = "robostack-jazzy" }
ros-jazzy-topic-tools = { channel = "robostack-jazzy" }

# ros 2 visualization/simulation pkgs
ros-jazzy-gz-ros2-control = { channel = "robostack-jazzy" }
ros-jazzy-ros-gz = { channel = "robostack-jazzy" }
ros-jazzy-ros-gz-bridge = { channel = "robostack-jazzy" }
ros-jazzy-ros-gz-image = { channel = "robostack-jazzy" }
ros-jazzy-ros-gz-sim = { channel = "robostack-jazzy" }
ros-jazzy-rqt-console = { channel = "robostack-jazzy" }
ros-jazzy-rqt-graph = { channel = "robostack-jazzy" }
ros-jazzy-rqt-tf-tree = { channel = "robostack-jazzy" }
ros-jazzy-rviz2 = { channel = "robostack-jazzy" }
ros-jazzy-rviz-default-plugins = { channel = "robostack-jazzy" }
ros-jazzy-xacro = { channel = "robostack-jazzy" }

# note: we can only depend on `video4linux`... on Linux. lol
#
# TODO: if we need this, put it back:
#
#
# [target.linux.dependencies]
# ros-jazzy-v4l2-camera = { channel = "robostack-jazzy" }

[pypi-dependencies]
colcon-ros-cargo = ">=0.2.0"
filelock = ">=3.20.0"
geopy = ">=2.4.1"
loguru = ">=0.7.3"
opencv-contrib-python = ">=4.11.0.86"
pygame = ">=2.6.1"
scipy = ">=1.15.2"
typer = ">=0.15.2"
